before:
  hooks:
    - go mod download

builds:
  - env:
      - CGO_ENABLED=0
    main: ./cmd/main.go
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

brews:
  - github:
      owner: ojizero
      name: homebrew-tap
    folder: Formula
    homepage:  https://github.com/ojizer/gofindup
    description: Simple find up utility
