name: Create new release
on:
  push:
    tags:
      - v*
jobs:
  release-binary:
    name: Release binary
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13

      - name: Check out code
        uses: actions/checkout@v2

      # The unshallow step is required for GoReleaser's
      # changelog generation to work correctly.
      - name: Unshallow
        run: git fetch --prune --unshallow

      - name: Get dependencies
        run: |
          go mod download
          go get github.com/mitchellh/gox

      - name: Run release
        uses: goreleaser/goreleaser-action@v1
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
